### ISSUE TITLE
Broken GitHub Button JS

### ISSUE THREAD

**Issue by rspeicher** [dzaporozhets/www.gitlabhq.com#2]
Upon visiting gitlabhq.com there's now two JavaScript errors because http://markdotto.github.com/github-buttons/github-btn.html?user=gitlabhq&repo=gitlabhq&type=fork&count=true is no longer available.

I'm not sure where the source for the current version of the site is, but it's apparently not this repo (last update was 2.2?), so I can't submit a pull request to fix this.

**Comment by dzaporozhets** [comment]
Fixed. thank you :)
