### ISSUE TITLE
Homepage not working

### ISSUE THREAD

**Issue by robbytaylor** [dzaporozhets/www.gitlabhq.com#3]
When visiting www.gitlabhq.com in Firefox on Ubuntu I get this:

http://i.imgur.com/W5QQa.png

Before being redirected to github:

http://i.imgur.com/fjvP5.png

**Comment by dzaporozhets** [comment]
sorry - I'll fix it soon

**Comment by dzaporozhets** [comment]
ok just removed counters for now
